CREATE TABLE cards (
	card_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	card_name text
);

CREATE TABLE cubes (
	cube_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
);

CREATE TABLE cube_card (
       cube_id int,
       card_id int
);


CREATE UNIQUE index cards_card_id_idx ON cards(card_id);
CREATE UNIQUE index cards_card_name_idx ON cards(card_name);
CREATE UNIQUE index cubes_cube_id_idx ON cubes(cube_id);

CREATE index cube_card_card_id_idx ON cube_card(card_id);
CREATE index cube_card_card_id_idx ON cube_card(card_id);
CREATE index cube_card_cube_id_idx ON cube_card(cube_id);

CLUSTER cards using cards_card_id_idx ;
CLUSTER cubes using cubes_cube_id_idx ;
CLUSTER cube_card using cube_card_card_id_idx ;
